export const SearchingDummyData = [
    'The cat sat on it',
    'The dog ran to him',
    'The bird flew away fast',
    'The fish swam in circles',
    'The horse galloped through fields',
    'The cow mooed at the farmer',
    'The sheep bleated in the meadow',
    'The goat ate the grass',
    'The pig oinked and snorted',
    'The duck quacked and waddled',
    'The sun set behind mountains',
    'The moon rose above the trees',
    'The stars twinkled in the sky',
    'The wind blew through the leaves',
    'The rain fell on the roof',
    'The snowflakes melted on contact',
    'The ice cream melted in heat',
    'The coffee spilled on table',
    'The tea was too hot',
    'The juice was too sweet',
    'The water was too cold',
    'The fire crackled in fireplace',
    'The smoke rose from chimney',
    'The ash fell on the ground',
    'The earthworm wriggled in soil',
    'The butterfly fluttered its wings',
    'The bee buzzed around flowers',
    'The ant crawled up the wall',
    'The spider spun its web',
    'The snake slithered through grass',
    'The lizard basked in sun',
    'The frog croaked in pond',
    'The fisherman caught a fish',
    'The hunter aimed at deer',
    'The farmer plowed the field',
    'The gardener watered the plants',
    'The chef cooked the meal',
    'The baker baked the bread',
    'The artist painted the picture',
    'The musician played the guitar',
    'The writer wrote the book',
    'The poet recited the poem',
    'The actor performed on stage',
    'The singer sang the song',
    'The dancer danced gracefully',
    'The athlete ran the race',
    'The coach trained the team',
    'The teacher taught the lesson',
    'The student learned the material'
]
